---
- name: i3wm
  apt: name="i3-wm" state=present update_cache=yes
  become: yes

- name: i3status
  apt: name="i3status" state=present update_cache=yes
  become: yes

- name: i3lock
  apt: name="i3lock" state=present update_cache=yes
  become: yes

- name: configuration directory
  file: 
    path: "/home/{{ user }}/.i3"
    state: directory
    mode: 0755
    owner: "{{ user }}"

- name: i3wm and statusbar configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ playbook_dir }}/../../i3/config', dest: '/home/{{ user }}/.i3/config' }
    - { src: '{{ playbook_dir }}/../../i3/i3status.conf', dest: '/home/{{ user }}/.i3/i3status.conf' }
    - { src: '{{ playbook_dir }}/../../i3/i3_layout_start.sh', dest: '/home/{{ user }}/i3_layout_start.sh' }

- name: copy custom caps compatibilty file for xkb to xkb/compat 
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ playbook_dir }}/../../xkb/custom_escape_to_mod3', dest: '/usr/share/X11/xkb/compat/escape_mod3' }
    - { src: '{{ playbook_dir }}/../../xkb/custom_complete_comp', dest: '/usr/share/X11/xkb/compat/complete' }
  become: yes




